const themes = {
  default: {
    name: "Default Blue",
    sentBg: "bg-blue-500",
    sentText: "text-white",
    recvBg: "bg-white dark:bg-gray-700",
    recvText: "text-gray-800 dark:text-white",
    recvBorder: "border border-gray-200 dark:border-gray-600",
    inputBg: "bg-white dark:bg-gray-800",
    headerBg: "bg-white dark:bg-gray-900",
    accent: "#378ADD",
    dot: "#378ADD",
  },
  amoled: {
    name: "AMOLED Black",
    sentBg: null,
    sentText: "text-blue-100",
    recvBg: null,
    recvText: "text-blue-200",
    recvBorder: null,
    inputBg: null,
    headerBg: null,
    accent: "#0066cc",
    dot: "#4da6ff",
    custom: {
      chatBg: "#000000",
      headerBg: "#050505",
      headerBorder: "#111111",
      inputBg: "#050505",
      inputBorder: "#111111",
      inputFieldBg: "#0d1117",
      inputFieldBorder: "#1a3a5c",
      sentBg: "#0066cc",
      sentText: "#e6f3ff",
      recvBg: "#0d1f33",
      recvText: "#99d0ff",
      sendBtn: "#0066cc",
      accentText: "#4da6ff",
    },
  },
  cream: {
    name: "Cream + Ink",
    custom: {
      chatBg: "#faf8f4",
      headerBg: "#f5f2ec",
      headerBorder: "#e8e2d8",
      inputBg: "#f5f2ec",
      inputBorder: "#e8e2d8",
      inputFieldBg: "#ede9e0",
      inputFieldBorder: "transparent",
      sentBg: "#2c2c2a",
      sentText: "#faf8f4",
      recvBg: "#ede9e0",
      recvText: "#2c2c2a",
      sendBtn: "#2c2c2a",
      accentText: "#888780",
      sentRadius: "10px 10px 0 10px",
      recvRadius: "0 10px 10px 10px",
    },
  },
  violet: {
    name: "Violet Nights",
    custom: {
      chatBg: "#12082a",
      headerBg: "#0d0520",
      headerBorder: "#2a1550",
      inputBg: "#0d0520",
      inputBorder: "#2a1550",
      inputFieldBg: "#1e0d40",
      inputFieldBorder: "#4a2880",
      sentBg: "#6633cc",
      sentText: "#f0e6ff",
      recvBg: "#1e0d40",
      recvText: "#c4a4ff",
      sendBtn: "#EF9F27",
      accentText: "#EF9F27",
    },
  },
  frost: {
    name: "Sky Frost",
    custom: {
      chatBg: "#e8eef8",
      headerBg: "#dde6f5",
      headerBorder: "#c8d5eb",
      inputBg: "#dde6f5",
      inputBorder: "#c8d5eb",
      inputFieldBg: "#c0d3ed",
      inputFieldBorder: "transparent",
      sentBg: "#185FA5",
      sentText: "#E6F1FB",
      recvBg: "#c0d3ed",
      recvText: "#0C447C",
      sendBtn: "#185FA5",
      accentText: "#1D9E75",
    },
  },
  sand: {
    name: "Warm Sand",
    custom: {
      chatBg: "#f7f3ec",
      headerBg: "#f0ebe0",
      headerBorder: "#e0d8c8",
      inputBg: "#f0ebe0",
      inputBorder: "#e0d8c8",
      inputFieldBg: "#e0d8c8",
      inputFieldBorder: "transparent",
      sentBg: "#0F6E56",
      sentText: "#E1F5EE",
      recvBg: "#d4ede5",
      recvText: "#085041",
      sendBtn: "#0F6E56",
      accentText: "#1D9E75",
    },
  },
  charcoal: {
    name: "Charcoal + Rose",
    custom: {
      chatBg: "#1a1a1a",
      headerBg: "#141414",
      headerBorder: "#2a2a2a",
      inputBg: "#141414",
      inputBorder: "#2a2a2a",
      inputFieldBg: "#222222",
      inputFieldBorder: "#3a3a3a",
      sentBg: "#993556",
      sentText: "#FBEAF0",
      recvBg: "#2a2a2a",
      recvText: "#c8c8c8",
      sendBtn: "#993556",
      accentText: "#ed93b1",
    },
  },
};

export default themes;